import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Layout from "../components/layout";



// Global styles
import "../styles/globals.scss";
import "../styles/partner.css";
import "../styles/chatbot.css";
import "../styles/herokenta.css";
import "../styles/brokers.css";


export default function App({ Component, pageProps }) {
  const router = useRouter();
  
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

   // ✅ Wrapper để fade mỗi lần đổi route
  const Page = (
    <div key={router.asPath} className="apple-route-fade">
      <Component {...pageProps} />
    </div>
  );

  // ===== Nếu page có getLayout → KHÔNG bọc Layout =====
  if (Component.getLayout) {
    return Component.getLayout(
      <>
        <Head>
          <title>Kenta Finance Connect</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
        </Head>

        <Component {...pageProps} />
      </>
    );
  }

  // ===== Các trang còn lại → bọc Layout bình thường =====
  return (
    <>
      <Head>
        <title>Kenta Finance Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}